### ISSUE TITLE
publicKey in serverVerifyAuth

### ISSUE THREAD

**Issue by AljoschaMeyer** [auditdrivencrypto/secret-handshake#13]
In `serverVerifyAuth`, the server [receives the longterm public key of the client](https://github.com/auditdrivencrypto/secret-handshake/blob/master/crypto.js#L163) by calling `state.remote.hello.slice(64, exports.client_auth_length)`. The resulting slice has length `112 bytes - 64 bytes = 48 bytes`. But isn't the public key only 32 bytes long?

**Comment by AljoschaMeyer** [comment]
Yup, turns out `state.remote.hello` is only 96 bytes long (or at least the equivalent buffer in my implementation is). Node just "conveniently" ignores that 112 is too long and simply sliced to the end of the buffer.

**Comment by dominictarr** [comment]
yes that is the sort of thing node does.
yes that should be the unboxed length not the boxed length. good spotting.
