### ISSUE TITLE
Old sodium-native causing compilation issues in Patchwork

### ISSUE THREAD

**Issue by christianbundy** [auditdrivencrypto/secret-handshake#18]
It looks like https://github.com/auditdrivencrypto/secret-handshake/commit/4682fe1a5caad405d406419b09a9b2844ddb4015 added sodium-native@1.x.x whereas we use sodium-native@2.x.x throughout the rest of the stack, which is currently breaking the build on Windows.

@dominictarr I don't see where sodium-native is being used, can it be removed from `package.json`?

**Comment by cryptix** [comment]
if it was on purpose, there should have been an explanation on the commit msg at least.

**Comment by dominictarr** [comment]
this is fixed in 1.1.18
