### ISSUE TITLE
add deterministic tests and test vectors

### ISSUE THREAD

**Issue by david415** [auditdrivencrypto/secret-handshake#5]
other language implementations of secret-handshake should share these test vectors. this would give implementers some confidence that they've done it correctly. additionally the binary compatibility among language implementations might prove useful.

**Comment by dominictarr** [comment]
I was just thinking that actually. 

If https://github.com/auditdrivencrypto/secret-handshake/blob/master/state.js was rewritten as pure functions, then we could generate extensive test vectors for each, persisted as, say, base64 strings inside json.

**Comment by david415** [comment]
yeah that sounds great.

**Comment by dominictarr** [comment]
done!
